[workspace]
members = ["sylvia", "sylvia-derive"]
exclude = ["examples/*"]
resolver = "2"

[workspace.package]
version = "1.3.3"

[workspace.dependencies]
anyhow = "1.0.95"
cosmwasm-schema = "2.2.0"
cosmwasm-std = "2.2.0"
cw-multi-test = "2.3.0"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
schemars = "0.8.21"
serde = { version = "1.0.217", default-features = false, features = ["derive"] }
sylvia-derive = { version = "1.3.3", path = "sylvia-derive" }
thiserror = "2.0.11"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
