[package]
name = "whitelist"
version = { workspace = true }
authors = ["Jan Wo≈∫niak <jan@confio.gmbh>"]
edition = { workspace = true }
description = "Coverage of whitelist sylvia message generation."
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/sylvia"
homepage = "https://cosmwasm.com"

[features]
mt = ["sylvia/mt"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["staking"] }
cosmwasm-schema = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
sylvia = { path = "../../../sylvia" }

[dev-dependencies]
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
